services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spplabs
    restart: unless-stopped

    expose:
      - "3000"

    networks:
      - proxy

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.spplabs.rule=Host(`spplabs.es`) || Host(`www.spplabs.es`) || Host(`api.spplabs.es`)"
      - "traefik.http.routers.spplabs.entrypoints=web"

      - "traefik.http.services.spplabs.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
