services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: spplabs
    restart: unless-stopped

    expose:
      - "3000"

    networks:
      - proxy

    environment:
      - GEOIP_DB_PATH=/opt/geoip/dbip

    volumes:
      - transformers-cache:/app/.cache/transformers
      - uploads-data:/app/public/uploads
      - /opt/geoip/dbip:/opt/geoip/dbip:ro

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.spplabs.rule=Host(`spplabs.es`) || Host(`www.spplabs.es`) || Host(`api.spplabs.es`)"
      - "traefik.http.routers.spplabs.entrypoints=web"

      - "traefik.http.services.spplabs.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true

volumes:
  transformers-cache:
  uploads-data:
